version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql_docker
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: root
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: poc_graphql
    ports:
      - 3306:3306
      - 33060:33060
